settings:
  title: 'Sturtz Network Status Page'
  url: 'https://status.sturtz.io' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 360 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: sturtz-search # unique identifier
    name: www.sturtz.io
    description: 'Sturtz Search' # default=empty
    url: 'https://www.sturtz.io' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: sturtz-cloud
    name: cloud.sturtz.io
    description: 'Secure Data Access'
    url: 'https://cloud.sturtz.io'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true